#!/bin/bash
#SBATCH --job-name=polypolish
#SBATCH -A jje_lab
#SBATCH -p highmem
#SBATCH --mem-per-cpu=10G
#SBATCH --cpus-per-task=32
#SBATCH --output="polypolish-MV25.out"

raw="/dfs7/jje/jenyuw/Non_melanogaster/raw"
filtered="/dfs7/jje/jenyuw/Non_melanogaster/filtered"
polishing="/dfs7/jje/jenyuw/Non_melanogaster/polishing_asm"
mapping="/dfs7/jje/jenyuw/Non_melanogaster/mapping"


:<<'SKIP'
/pub/jenyuw/Software/bwa-mem2/bwa-mem2 index ${input}
/pub/jenyuw/Software/bwa-mem2/bwa-mem2 mem -t $SLURM_CPUS_PER_TASK -a ${input} ${filtered}/illumina_MV25_male.R1.filtered.fastq.gz >${mapping}/illumina_MV25_POLCA-polished.R1.sam
/pub/jenyuw/Software/bwa-mem2/bwa-mem2 mem -t $SLURM_CPUS_PER_TASK -a ${input} ${filtered}/illumina_MV25_male.R2.filtered.fastq.gz >${mapping}/illumina_MV25_POLCA-polished.R2.sam

## The following failed because of OOM kill even though the hugemem partition was used.
## Move everything to our Thoth server with 1TB RAM. However, it even got OOM killed!!!!!!
polypolish filter --low 1 --high 99 --in1 ${mapping}/illumina_MV25_POLCA-polished.R1.sam \
--in2 ${mapping}/illumina_MV25_POLCA-polished.R2.sam \
--out1 ${mapping}/illumina_MV25_POLCA-polished.R1.filtered.sam \
--out2 ${mapping}/illumina_MV25_POLCA-polished.R2.filtered.sam


polypolish polish ${input} ${mapping}/illumina_MV25_POLCA-polished.R1.filtered.sam ${mapping}/illumina_MV25_POLCA-polished.R2.filtered.sam > ${polishing}/Dpse_MV25_hifiasm_12-2_hap1_polypolish-polished.fasta
SKIP

## Solution 2: split the sam files by contigs
## Problem with sorting by coordinates: https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#does-the-order-of-alignments-in-the-sam-file-matter
#use the samtools 'sort by read name' option (-n) to make them compatible with Polypolish --> This did not work either
## --> Avoid converting bam and sorting.

input="${polishing}/dorado-polished_Dpse_MV25_hifiasm_12-2_hap1.fasta.PolcaCorrected.fa"
R1="${filtered}/illumina_MV25_male.R1.filtered.fastq.gz"
R2="${filtered}/illumina_MV25_male.R2.filtered.fastq.gz"

/pub/jenyuw/Software/bwa-mem2/bwa-mem2 index ${input}
## saving in sam format is super inefficient and takes up a lot of space.
/pub/jenyuw/Software/bwa-mem2/bwa-mem2 mem -t $SLURM_CPUS_PER_TASK -a ${input} ${R1} |\
samtools view -bh -o ${mapping}/illumina_MV25_POLCA-polished.R1.bam
/pub/jenyuw/Software/bwa-mem2/bwa-mem2 mem -t $SLURM_CPUS_PER_TASK -a ${input} ${R2} |\
samtools view -bh -o ${mapping}/illumina_MV25_POLCA-polished.R2.bam

## Subsetting the bam files by contigs failed because one read can be aligned to multiple contigs!!!
## Remove secondary alignments on different contigs. "filter_secondary.sh" was mostly generated by Gemini.
## output a sorted bam file so it can be indexed.
./filter_secondary.sh ${mapping}/illumina_MV25_POLCA-polished.R1.bam  ${mapping}/illumina_MV25_POLCA-polished.R1.filtered.bam 16
./filter_secondary.sh ${mapping}/illumina_MV25_POLCA-polished.R2.bam  ${mapping}/illumina_MV25_POLCA-polished.R2.filtered.bam 16
samtools index -@ $SLURM_CPUS_PER_TASK ${mapping}/illumina_MV25_POLCA-polished.R1.filtered.bam
samtools index -@ $SLURM_CPUS_PER_TASK ${mapping}/illumina_MV25_POLCA-polished.R2.filtered.bam

samtools faidx ${input}

contigs=$(gawk '{print $1}' ${input}.fai)

for i in ${contigs}
do
    for j in "R1" "R2"
    do
    #gawk -v contig="${i}" ' $3 == contig { print } ' ${mapping}/illumina_MV25_POLCA-polished.${j}.sam > ${mapping}/illumina_MV25_POLCA-polished.${j}.${i}.sam ### ARRRRRRRR, don't use sam because it is toooooo inefficient
    #${mapping}/illumina_MV25_POLCA-polished.${j}.filtered.bam
    samtools view -@ $(($SLURM_CPUS_PER_TASK / 2)) -bh ${mapping}/illumina_MV25_POLCA-polished.R1.filtered.tmp.bam ${i} |\
    samtools sort -n -@ $(($SLURM_CPUS_PER_TASK / 2))  -m 2G -o ${mapping}/illumina_MV25_POLCA-polished.${j}.${i}.filtered.sam
    done
done

for i in ${contigs}; do
seqkit grep -p ${i} ${input} > ${polishing}/dorado-polished_Dpse_MV25_hifiasm_12-2_hap1.${i}.fasta
polypolish filter \
--in1 ${mapping}/illumina_MV25_POLCA-polished.R1.${i}.filtered.sam \
--in2 ${mapping}/illumina_MV25_POLCA-polished.R2.${i}.filtered.sam \
--out1 ${mapping}/illumina_MV25_POLCA-polished.R1.${i}.polyfiltered.sam \
--out2 ${mapping}/illumina_MV25_POLCA-polished.R2.${i}.polyfiltered.sam
polypolish polish ${polishing}/dorado-polished_Dpse_MV25_hifiasm_12-2_hap1.${i}.fasta \
${mapping}/illumina_MV25_POLCA-polished.R1.${i}.polyfiltered.sam \
${mapping}/illumina_MV25_POLCA-polished.R2.${i}.polyfiltered.sam > ${polishing}/Dpse_MV25_hifiasm_12-2_hap1_polypolish-polished.${i}.fasta
echo "Finished polishing contig ${i}"
done